name: todo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
  # sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  google_mobile_ads: ^3.1.0
  import_sorter: ^4.6.0
  uuid: ^4.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  tab_indicator_styler: ^2.0.0
  google_sign_in: ^6.2.1
  flutter_signin_button: ^2.0.0
  sign_in_with_apple: ^5.0.0
  flutter_animate: ^4.5.0
  sign_button: ^2.0.6
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
