// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLhLmm22eGfI30DVPAsOAdyccfaMQV25Y',
    appId: '1:854722410279:web:46b4bc3f9e1924235fdb02',
    messagingSenderId: '854722410279',
    projectId: 'todo-ea5b5',
    authDomain: 'todo-ea5b5.firebaseapp.com',
    storageBucket: 'todo-ea5b5.appspot.com',
    measurementId: 'G-29516C4FT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3tm33ktcbZlYU1XnT4clY9MwdKWRj7_o',
    appId: '1:854722410279:android:043d2d97cd11303e5fdb02',
    messagingSenderId: '854722410279',
    projectId: 'todo-ea5b5',
    storageBucket: 'todo-ea5b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuxaOUrxlQKqJnT3XKX1pMo7S9scwdSHY',
    appId: '1:854722410279:ios:0dc17d4377df2ea75fdb02',
    messagingSenderId: '854722410279',
    projectId: 'todo-ea5b5',
    storageBucket: 'todo-ea5b5.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
